Update AutoRun.yaml
updating report config

diff --git a/.github/workflows/AutoRun.yaml b/.github/workflows/AutoRun.yaml
--- a/.github/workflows/AutoRun.yaml
+++ b/.github/workflows/AutoRun.yaml
@@ -18,8 +18,15 @@ jobs:
      id: packaging-jar
      shell: bash
      run: mvn clean install
-   - uses: actions/upload-artifact@v2  # upload test results
-     if: success() || failure()        # run this step even if previous step failed
+   - name: Test Report
+     uses: phoenix-actions/test-reporting@v8
+     id: test-report               # Set ID reference for step
+     if: success() || failure()    # run this step even if previous step failed
      with:
-      name: test-results
-      path: jest-junit.xml
+      name: JEST Tests            # Name of the check run which will be created
+      path: reports/jest-*.xml    # Path to test results
+      reporter: jest-junit        # Format of test results
+
+   - name: Read output variables
+     run: |
+       echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
